# <center> ANALISIS DE DATOS DE LA EMPRESA TIMARAN </center>

## <center> **Realizado por: Jessica Tatiana Navarro Barreto** </center>

### <center> *Analisis de Ventas* </center>

### <center> **Faro consultores** </center>


### <center> ***FARO CONSULTORES Y ASESORES S.A.S*** </center>

#### <center> **Fecha:** 06 de Junio de 2026 </center>

## **Carga de Data**

##### **Primero realizamos la carga de la informacion en el df**

In [301]:
import pandas as pd
from IPython.display import display

excelPath = "Data\\Informacion sin limpiar.xlsx"

df_sin_limpiar = pd.read_excel(
    excelPath,
    sheet_name = "Análisis de ventas",
    header = 3,
    index_col = 0)

df_sin_limpiar = df_sin_limpiar.reset_index()# Eliminar la columna de índice

display(df_sin_limpiar.head())

,PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,[2542] ENVASE SADMAN TRANSP 105 ML PLATA ...,ENVASE,SADMAN,105 ML,54
1,[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,72
2,[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,72
3,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NaN,NaN
4,[2278] A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

##### **Separamos las columnas de productos para hacer la clasificacion**

In [302]:
df_productos = df_sin_limpiar.iloc[:, 0:5]

display(df_productos.head())

,PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,[2542] ENVASE SADMAN TRANSP 105 ML PLATA ...,ENVASE,SADMAN,105 ML,54
1,[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,72
2,[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,72
3,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NaN,NaN
4,[2278] A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

##### **Cambiamos a mayuscula el encabezado**

In [303]:
df_productos.columns = df_productos.columns.str.upper()# Convertir los nombres del emcabezado de las columnas a mayúsculas

display(df_productos.head())

,PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,[2542] ENVASE SADMAN TRANSP 105 ML PLATA ...,ENVASE,SADMAN,105 ML,54
1,[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,72
2,[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,72
3,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NaN,NaN
4,[2278] A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

##### **Cambiar los valores de las columnas a mayúsculas**

In [304]:
# Convertir los valores de las columnas a minúsculas
df_productos["PRODUCTO"] = df_productos["PRODUCTO"].str.upper()
df_productos["CLASIFICACION I"] = df_productos["CLASIFICACION I"].str.upper()
df_productos["CLASIFICACION II"] = df_productos["CLASIFICACION II"].str.upper()
df_productos["CLASIFICACION III"] = df_productos["CLASIFICACION III"].str.upper()
df_productos["CLASIFICACION IV"] = df_productos["CLASIFICACION IV"].str.upper()

display(df_productos.head())

,PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,[2542] ENVASE SADMAN TRANSP 105 ML PLATA ...,ENVASE,SADMAN,105 ML,NaN
1,[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,NaN
2,[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,NaN
3,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NaN,NaN
4,[2278] A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

##### **Separamos los codigos de los productos**

In [305]:
df_productos["CODIGO_PRODUCTO"] = (
    df_productos["PRODUCTO"]
    .str.extract(r"\[(.*?)\]", expand=False)
    .astype("string")
    .str.strip()
)

df_productos["NOMBRE_PRODUCTO"] = (
    df_productos["PRODUCTO"]
    .str.replace(r"\[.*?\]\s*", "", regex=True)
    .str.strip()
)

# Eliminar la columna original que tenía código + nombre juntos
df_productos = df_productos.drop(columns=["PRODUCTO"])

# Reordenar columnas
df_productos = df_productos[
    [
        "CODIGO_PRODUCTO",
        "NOMBRE_PRODUCTO",
        "CLASIFICACION I",
        "CLASIFICACION II",
        "CLASIFICACION III",
        "CLASIFICACION IV"
    ]
]

display(df_productos.head())

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2542,ENVASE SADMAN TRANSP 105 ML PLATA CROMADO X 54...,ENVASE,SADMAN,105 ML,NaN
1,2610,ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,NaN
2,2608,ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,NaN
3,2229,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NaN,NaN
4,2278,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

##### **Limpiamos los espacios de inio y fin y entre palabras del texto**

In [306]:
columnas_limpiar = [
    "NOMBRE_PRODUCTO",
    "CLASIFICACION I",
    "CLASIFICACION II",
    "CLASIFICACION III",
    "CLASIFICACION IV"
]

df_productos[columnas_limpiar] = df_productos[columnas_limpiar].apply(
    lambda col: col.str.strip().str.replace(r"\s+", " ", regex=True)
)

df_productos["CODIGO_PRODUCTO"] = (
    df_productos["CODIGO_PRODUCTO"]
    .astype("string")
    .str.replace(r"\s+", "", regex=True)
)

display(df_productos.head())

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2542,ENVASE SADMAN TRANSP 105 ML PLATA CROMADO X 54...,ENVASE,SADMAN,105 ML,NaN
1,2610,ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,NaN
2,2608,ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,NaN
3,2229,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NaN,NaN
4,2278,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

In [307]:
df_productos["CLASIFICACION I"].unique()

<StringArray>
[ 'ENVASE',   'FUNDA', 'ESENCIA',  'ACEITE', 'ALCOHOL',   'CREMA', 'MAQUINA',
    'CAJA', 'FIJADOR', 'GLITTER',  'MALETA',    'STCK',    'TAPA', 'VALVULA']
Length: 14, dtype: str

In [308]:
df_productos["CLASIFICACION III"].value_counts()

CLASIFICACION III
30 ML               157
100 ML              124
50 ML                91
60 ML                82
CAROLINA HERRERA     55
                   ...
DAVID BECKHAM         1
EMMIR                 1
JUICY COUTURE         1
JOOP                  1
MARIE FARINA          1
Name: count, Length: 201, dtype: int64

In [309]:
# Crear tabla maestra de productos
df_productos_maestro = df_productos.copy()

df_productos_maestro = df_productos_maestro[
    [
        "CODIGO_PRODUCTO",
        "NOMBRE_PRODUCTO",
        "CLASIFICACION I",
        "CLASIFICACION II",
        "CLASIFICACION III",
        "CLASIFICACION IV"
    ]
]

display(df_productos_maestro.head())

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2542,ENVASE SADMAN TRANSP 105 ML PLATA CROMADO X 54...,ENVASE,SADMAN,105 ML,NaN
1,2610,ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,NaN
2,2608,ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,NaN
3,2229,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NaN,NaN
4,2278,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

##### **Verificar los datos null del df**

In [310]:
df_productos_maestro.isnull().sum()

CODIGO_PRODUCTO         0
NOMBRE_PRODUCTO         0
CLASIFICACION I         0
CLASIFICACION II      868
CLASIFICACION III     937
CLASIFICACION IV     1529
dtype: int64

##### **Cambiar los valores Null por NO APLICA**

In [311]:
columnas_rellenar = [
    "CLASIFICACION II",
    "CLASIFICACION III",
    "CLASIFICACION IV"
]

# Convertir espacios vacíos o textos vacíos en valores nulos reales
df_productos_maestro[columnas_rellenar] = (
    df_productos_maestro[columnas_rellenar]
    .replace(r"^\s*$", pd.NA, regex=True)
)

# Ahora sí llenar con NO APLICA
df_productos_maestro[columnas_rellenar] = (
    df_productos_maestro[columnas_rellenar]
    .fillna("NO APLICA")
)

In [312]:
df_productos_maestro.isnull().sum()

CODIGO_PRODUCTO      0
NOMBRE_PRODUCTO      0
CLASIFICACION I      0
CLASIFICACION II     0
CLASIFICACION III    0
CLASIFICACION IV     0
dtype: int64

In [313]:
df_productos_maestro["CLASIFICACION II"].value_counts(dropna=False)

CLASIFICACION II
NO APLICA          868
ESENCIA GENERAL    520
ESENCIA NICHO      327
CILINDRO            68
SALVAJE             36
                  ...
XER                  1
FRASCO               1
PROBADOR             1
EMIR                 1
KALIFA               1
Name: count, Length: 93, dtype: int64

In [314]:
df_productos_maestro["CLASIFICACION III"].value_counts(dropna=False)

CLASIFICACION III
NO APLICA        937
30 ML            157
100 ML           124
50 ML             91
60 ML             82
                ...
DAVID BECKHAM      1
EMMIR              1
JUICY COUTURE      1
JOOP               1
MARIE FARINA       1
Name: count, Length: 202, dtype: int64

In [315]:
df_productos_maestro.isnull().sum()

CODIGO_PRODUCTO      0
NOMBRE_PRODUCTO      0
CLASIFICACION I      0
CLASIFICACION II     0
CLASIFICACION III    0
CLASIFICACION IV     0
dtype: int64

In [316]:
display(
    df_productos_maestro[
        (df_productos_maestro["CLASIFICACION II"] == "NO APLICA") |
        (df_productos_maestro["CLASIFICACION III"] == "NO APLICA") |
        (df_productos_maestro["CLASIFICACION IV"] == "NO APLICA")
    ].head(20)
)

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2542,ENVASE SADMAN TRANSP 105 ML PLATA CROMADO X 54...,ENVASE,SADMAN,105 ML,NO APLICA
1,2610,ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,NO APLICA
2,2608,ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,NO APLICA
3,2229,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NO APLICA,NO APLICA
58,1425,BALA ALUMINIO DORADA X 300 UND,ENVASE,BALA ALUMINIO,NO APLICA,NO APLICA
59,1424,BALA ALUMINIO NEGRA X 282 UND,ENVASE,BALA ALUMINIO,NO APLICA,NO APLICA
60,0020,BALA ALUMINIO PLATEADA X 300 UND,ENVASE,BALA ALUMINIO,NO APLICA,NO APLICA
62,2670,BAMBU FINAL,ESENCIA,ESENCIA INDUSTRIAL,DIFUSORES,NO APLICA
102,2449,BOQUILLA MAQUINA GRAFADORA # 15,MAQUINA,NO APLICA,NO APLICA,NO APLICA
103,2228,BOQUILLA MAQUINA GRAFADORA # 18,MAQUINA,NO APLICA,NO APLICA,NO APLICA
104,2227,BOQUILLA MAQUINA GRAFADORA # 20,MAQUINA,NO APLICA,NO APLICA,NO APLICA
125,2782,CAJA CILINDRICA BLANCA 10 ML X 539 UND,CAJA,CILINDRICA,10 ML,NO APLICA
126,2780,CAJA CILINDRICA BLANCA 100 ML X 120 UND,CAJA,CILINDRICA,100 ML,NO APLICA
127,0005,CAJA MADERA,CAJA,MADERA,NO APLICA,NO APLICA
128,0008,CAJA PARA CILINDRO 1OZ DORADO,CAJA,CILINDRO,1 OZ,NO APLICA
129,0009,CAJA PARA CILINDRO 1OZ FUCSIA,CAJA,CILINDRO,1 OZ,NO APLICA
130,0006,CAJA PARA CILINDRO 1OZ NEGRA,CAJA,CILINDRO,1 OZ,NO APLICA
131,0007,CAJA PARA CILINDRO 1OZ PLATA,CAJA,CILINDRO,1 OZ,NO APLICA
132,0010,CAJA PARA CILINDRO 2OZ DORADO,CAJA,CILINDRO,2 OZ,NO APLICA
133,0011,CAJA PARA CILINDRO 2OZ FUCSIA,CAJA,CILINDRO,2 OZ,NO APLICA

In [317]:
df_productos_maestro.to_excel(
    "Data/Tabla_Maestra_Productos.xlsx",
    sheet_name="Productos",
    index=False
)

pilas