# <center> ANALISIS DE DATOS DE LA EMPRESA TIMARAN </center>

## <center> **Realizado por: Jessica Tatiana Navarro Barreto** </center>

### <center> *Analisis de Ventas* </center>

### <center> **Faro consultores** </center>


### <center> ***FARO CONSULTORES Y ASESORES S.A.S*** </center>

#### <center> **Fecha:** 06 de Junio de 2026 </center>

##### **Carga de archivo de ventas**

In [1]:
import pandas as pd

# ==============================
# 1. RUTAS DE ARCHIVOS
# ==============================

ruta_reporte_ventas = "Data\\Tabla Analisis de ventas.xlsx"
ruta_tabla_maestra = "Data\\Tabla_Maestra_Productos.xlsx"
ruta_salida_powerbi = "Resultado\\Ventas_Limpias_PowerBI.xlsx"

##### **Carga de tabla maestra**

In [2]:
# ==============================
# 2. CARGAR TABLA MAESTRA
# ==============================

df_maestro = pd.read_excel(
    ruta_tabla_maestra,
    sheet_name="Productos"
)

# Normalizar encabezados
df_maestro.columns = (
    df_maestro.columns
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True)
)

# Asegurar que el código sea texto
df_maestro["CODIGO_PRODUCTO"] = (
    df_maestro["CODIGO_PRODUCTO"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", "", regex=True)
)

display(df_maestro.head())

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2542,ENVASE SADMAN TRANSP 105 ML PLATA CROMADO X 54...,ENVASE,SADMAN,105 ML,NO APLICA
1,2610,ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,NO APLICA
2,2608,ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,NO APLICA
3,2229,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NO APLICA,NO APLICA
4,2278,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

##### **Carga de reporte de ventas**

In [3]:
# ==============================
# 3. CARGAR REPORTE ORIGINAL DE VENTAS
# ==============================

df_ventas_original = pd.read_excel(
    ruta_reporte_ventas,
    sheet_name="Análisis de ventas",
    header=2,
    index_col=0
)

df_ventas_original = df_ventas_original.drop(df_ventas_original.index[[0, 1]]) #Elimina las filas del emcabezado que no necesito

ultima_columna = df_ventas_original.columns[-1] #Busco la última columna, que es la que tiene el total, para eliminarla porque no me sirve

df_ventas_original = df_ventas_original.drop(columns=[ultima_columna])#Elimino la última columna

display(df_ventas_original.head(10))

,mayo 2025,junio 2025,julio 2025,agosto 2025,septiembre 2025,octubre 2025,noviembre 2025,diciembre 2025,enero 2026,febrero 2026,marzo 2026,abril 2026,mayo 2026,junio 2026
[2542] ENVASE SADMAN TRANSP 105 ML PLATA CROMADO X 54 UND,NaN,NaN,NaN,NaN,NaN,6,NaN,8,NaN,46,NaN,NaN,1,NaN
[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,54,NaN
[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186,90,12,NaN
[2229] 180 FUNDAS SURTIDAS X 6 COLORES,73,56,157,160,201,164,147,173,144,134,183,126,168,48
[2278] A MILKSHAKE PLEASE DM,193053,146280,137350,223220,228960,274290,245700,235090,268160,175929,323883,321585,277610,80200
[2834] ACEITE DE CASTOR P40 - FINDET ARH/52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,1370
[0252] ACQUA FRESCA HM,108910,109915,81860,71640,166441,102190,102460,88830,93120,74230,129781,108700,88465,30250
[509] ADDICTIVE VIBE HM,198785,182400,219280,170521,253010,195280,233260,207311,184060,134350,216290,234821,136500,36780
[0723] ADELINE DM,44195,46097,52230,28890,46680,42640,37510,33530,39370,40470,32920,37651,30070,10050
[400] ADIVINA DM,20035,22120,14880,21710,56210,12140,24910,12610,25410,14270,43940,30440,17930,3230

##### **Colocar nombre de la columna productos**

In [4]:
df_ventas_original = df_ventas_original.reset_index()

df_ventas_original = df_ventas_original.rename(
    columns={"index": "PRODUCTO"}
)

display(df_ventas_original.head())

,PRODUCTO,mayo 2025,junio 2025,julio 2025,agosto 2025,septiembre 2025,octubre 2025,noviembre 2025,diciembre 2025,enero 2026,febrero 2026,marzo 2026,abril 2026,mayo 2026,junio 2026
0,[2542] ENVASE SADMAN TRANSP 105 ML PLATA ...,NaN,NaN,NaN,NaN,NaN,6,NaN,8,NaN,46,NaN,NaN,1,NaN
1,[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,54,NaN
2,[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186,90,12,NaN
3,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,73,56,157,160,201,164,147,173,144,134,183,126,168,48
4,[2278] A MILKSHAKE PLEASE DM,193053,146280,137350,223220,228960,274290,245700,235090,268160,175929,323883,321585,277610,80200

##### **Cambiamos a mayuscula el encabezado**

In [5]:
df_ventas_original.columns = df_ventas_original.columns.str.upper()# Convertir los nombres del emcabezado de las columnas a mayúsculas

display(df_ventas_original.head())

,PRODUCTO,MAYO 2025,JUNIO 2025,JULIO 2025,AGOSTO 2025,SEPTIEMBRE 2025,OCTUBRE 2025,NOVIEMBRE 2025,DICIEMBRE 2025,ENERO 2026,FEBRERO 2026,MARZO 2026,ABRIL 2026,MAYO 2026,JUNIO 2026
0,[2542] ENVASE SADMAN TRANSP 105 ML PLATA ...,NaN,NaN,NaN,NaN,NaN,6,NaN,8,NaN,46,NaN,NaN,1,NaN
1,[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,54,NaN
2,[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,186,90,12,NaN
3,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,73,56,157,160,201,164,147,173,144,134,183,126,168,48
4,[2278] A MILKSHAKE PLEASE DM,193053,146280,137350,223220,228960,274290,245700,235090,268160,175929,323883,321585,277610,80200

##### **Verificar el numero de fila y columnas**

In [6]:
print("Filas y columnas:", df_ventas_original.shape)

print("Columnas:")
print(df_ventas_original.columns)

Filas y columnas: (2415, 15)
Columnas:
Index(['PRODUCTO', 'MAYO 2025', 'JUNIO 2025', 'JULIO 2025', 'AGOSTO 2025',
       'SEPTIEMBRE 2025', 'OCTUBRE 2025', 'NOVIEMBRE 2025', 'DICIEMBRE 2025',
       'ENERO 2026', 'FEBRERO 2026', 'MARZO 2026', 'ABRIL 2026', 'MAYO 2026',
       'JUNIO 2026'],
      dtype='str')

##### **Cantidad de valorez null y vacios**

In [7]:
df_revision_nulls = pd.DataFrame({
    "COLUMNA": df_ventas_original.columns,
    "CANTIDAD_NULL": df_ventas_original.isnull().sum().values,
    "CANTIDAD_VACIOS": [
        df_ventas_original[col]
        .astype("string")
        .str.strip()
        .eq("")
        .sum()
        for col in df_ventas_original.columns
    ]
})

df_revision_nulls["TOTAL_NULL_Y_VACIOS"] = (
    df_revision_nulls["CANTIDAD_NULL"] + df_revision_nulls["CANTIDAD_VACIOS"]
)

display(df_revision_nulls)

            COLUMNA  CANTIDAD_NULL  CANTIDAD_VACIOS  TOTAL_NULL_Y_VACIOS
0          PRODUCTO              0                0                    0
1         MAYO 2025            546                0                  546
2        JUNIO 2025            566                0                  566
3        JULIO 2025            500                0                  500
4       AGOSTO 2025            536                0                  536
5   SEPTIEMBRE 2025            484                0                  484
6      OCTUBRE 2025            531                0                  531
7    NOVIEMBRE 2025            451                0                  451
8    DICIEMBRE 2025            458                0                  458
9        ENERO 2026            509                0                  509
10     FEBRERO 2026            540                0                  540
11       MARZO 2026            516                0                  516
12       ABRIL 2026            512                0                  512
13        MAYO 2026            550                0                  550
14       JUNIO 2026            919                0                  919

##### **Limpiamos los espacios de los productos**

In [8]:
df_ventas_original["PRODUCTO"] = (
    df_ventas_original["PRODUCTO"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

display(df_ventas_original[["PRODUCTO"]].head(10))

                                            PRODUCTO
0  [2542] ENVASE SADMAN TRANSP 105 ML PLATA CROMA...
1       [2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND
2        [2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND
3             [2229] 180 FUNDAS SURTIDAS X 6 COLORES
4                       [2278] A MILKSHAKE PLEASE DM
5        [2834] ACEITE DE CASTOR P40 - FINDET ARH/52
6                             [0252] ACQUA FRESCA HM
7                            [509] ADDICTIVE VIBE HM
8                                  [0723] ADELINE DM
9                                   [400] ADIVINA DM

In [9]:
# ==============================
# 3. EXTRAER CODIGO_PRODUCTO
# ==============================
df_ventas_original["CODIGO_PRODUCTO"] = (
    df_ventas_original["PRODUCTO"]
    .str.extract(r"\[(.*?)\]", expand=False)
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", "", regex=True)
)

display(df_ventas_original[["PRODUCTO", "CODIGO_PRODUCTO"]].head(10))

                                            PRODUCTO CODIGO_PRODUCTO
0  [2542] ENVASE SADMAN TRANSP 105 ML PLATA CROMA...            2542
1       [2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND            2610
2        [2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND            2608
3             [2229] 180 FUNDAS SURTIDAS X 6 COLORES            2229
4                       [2278] A MILKSHAKE PLEASE DM            2278
5        [2834] ACEITE DE CASTOR P40 - FINDET ARH/52            2834
6                             [0252] ACQUA FRESCA HM            0252
7                            [509] ADDICTIVE VIBE HM             509
8                                  [0723] ADELINE DM            0723
9                                   [400] ADIVINA DM             400

In [10]:
productos_sin_codigo = df_ventas_original[
    df_ventas_original["CODIGO_PRODUCTO"].isna()
]

display(productos_sin_codigo[["PRODUCTO"]])

                 PRODUCTO
830   FLETE INTERNACIONAL
2300           Transporte

In [11]:
# Eliminar productos que no tienen código
df_ventas_original = df_ventas_original[
    df_ventas_original["CODIGO_PRODUCTO"].notna()
].copy()

# Reiniciar índice
df_ventas_original = df_ventas_original.reset_index(drop=True)

In [12]:
productos_sin_codigo = df_ventas_original[
    df_ventas_original["CODIGO_PRODUCTO"].isna()
]

display(productos_sin_codigo[["PRODUCTO"]])

Empty DataFrame
Columns: [PRODUCTO]
Index: []

In [13]:
# ==============================
# 5. IDENTIFICAR COLUMNAS DE MESES
# ==============================

columnas_meses = [
    col for col in df_ventas_original.columns
    if col not in ["PRODUCTO", "CODIGO_PRODUCTO"]
]

print("Columnas de meses encontradas:")
print(columnas_meses)

print("Cantidad de columnas de meses:", len(columnas_meses))

Columnas de meses encontradas:
['MAYO 2025', 'JUNIO 2025', 'JULIO 2025', 'AGOSTO 2025', 'SEPTIEMBRE 2025', 'OCTUBRE 2025', 'NOVIEMBRE 2025', 'DICIEMBRE 2025', 'ENERO 2026', 'FEBRERO 2026', 'MARZO 2026', 'ABRIL 2026', 'MAYO 2026', 'JUNIO 2026']
Cantidad de columnas de meses: 14

In [14]:
# ==============================
# 5.1 VALIDAR VALORES NO NUMÉRICOS
# ==============================

columnas_con_problemas = []

for col in columnas_meses:
    datos_convertidos = pd.to_numeric(df_ventas_original[col], errors="coerce")

    valores_problematicos = df_ventas_original[
        df_ventas_original[col].notna() & datos_convertidos.isna()
    ]

    if len(valores_problematicos) > 0:
        columnas_con_problemas.append(col)
        print(f"Problemas en la columna: {col}")
        display(valores_problematicos[["PRODUCTO", col]].head(10))

print("Columnas con problemas:")
print(columnas_con_problemas)

Columnas con problemas:
[]

In [15]:
# ==============================
# 5.2 CONVERTIR COLUMNAS DE MESES A NUMÉRICAS
# ==============================

df_ventas_original[columnas_meses] = df_ventas_original[columnas_meses].apply(
    pd.to_numeric,
    errors="coerce"
)

In [16]:
# ==============================
# 5.3 VERIFICAR TIPOS DE DATOS
# ==============================

display(df_ventas_original[columnas_meses].dtypes)

MAYO 2025          float64
JUNIO 2025         float64
JULIO 2025         float64
AGOSTO 2025        float64
SEPTIEMBRE 2025    float64
OCTUBRE 2025       float64
NOVIEMBRE 2025     float64
DICIEMBRE 2025     float64
ENERO 2026         float64
FEBRERO 2026       float64
MARZO 2026         float64
ABRIL 2026         float64
MAYO 2026          float64
JUNIO 2026         float64
dtype: object

In [17]:
# ==============================
# 5.4 REVISAR NULLS DESPUÉS DE CONVERTIR
# ==============================

df_nulls_meses = (
    df_ventas_original[columnas_meses]
    .isnull()
    .sum()
    .reset_index()
)

df_nulls_meses.columns = ["MES", "CANTIDAD_NULL"]

display(df_nulls_meses)

                MES  CANTIDAD_NULL
0         MAYO 2025            545
1        JUNIO 2025            564
2        JULIO 2025            499
3       AGOSTO 2025            534
4   SEPTIEMBRE 2025            482
5      OCTUBRE 2025            529
6    NOVIEMBRE 2025            449
7    DICIEMBRE 2025            456
8        ENERO 2026            507
9      FEBRERO 2026            538
10       MARZO 2026            515
11       ABRIL 2026            510
12        MAYO 2026            548
13       JUNIO 2026            917

In [18]:
# ==============================
# 6. CONVERTIR TABLA DE FORMATO ANCHO A FORMATO LARGO
# ==============================

df_ventas_largo = df_ventas_original.melt(
    id_vars=["CODIGO_PRODUCTO", "PRODUCTO"],
    value_vars=columnas_meses,
    var_name="PERIODO",
    value_name="CANTIDAD_FACTURADA"
)

display(df_ventas_largo.head(20))

,CODIGO_PRODUCTO,PRODUCTO,PERIODO,CANTIDAD_FACTURADA
0,2542,[2542] ENVASE SADMAN TRANSP 105 ML PLATA CROMA...,MAYO 2025,NaN
1,2610,[2610] ENVASE SALVAJE 100 ML FUCSIA X 72 UND,MAYO 2025,NaN
2,2608,[2608] ENVASE SALVAJE 100 ML NEGRO X 72 UND,MAYO 2025,NaN
3,2229,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,MAYO 2025,73.0
4,2278,[2278] A MILKSHAKE PLEASE DM,MAYO 2025,193053.0
5,2834,[2834] ACEITE DE CASTOR P40 - FINDET ARH/52,MAYO 2025,NaN
6,0252,[0252] ACQUA FRESCA HM,MAYO 2025,108910.0
7,509,[509] ADDICTIVE VIBE HM,MAYO 2025,198785.0
8,0723,[0723] ADELINE DM,MAYO 2025,44195.0
9,400,[400] ADIVINA DM,MAYO 2025,20035.0
10,372,[372] ADREA HM,MAYO 2025,125210.0
11,291,[291] ADRIAN HM,MAYO 2025,137494.0
12,287,[287] ADRIANA DM,MAYO 2025,29245.0
13,2097,[2097] ADVENTUROUS SKIPPER HM,MAYO 2025,9170.0
14,2166,[2166] AEDEN UNISEX,MAYO 2025,4050.0
15,309,[309] AFFRIKA DM,MAYO 2025,40630.0
16,310,[310] AFRIKANO HM,MAYO 2025,3980.0
17,485,[485] AFRODISIO HM,MAYO 2025,23760.0
18,273,[273] AGUAMARINA HM,MAYO 2025,17970.0
19,693,[693] ALAMBRA LINA DM,MAYO 2025,10580.0

In [19]:
print("Filas y columnas:", df_ventas_largo.shape)

Filas y columnas: (33782, 4)

In [20]:
# Eliminar registros sin venta
df_ventas_largo = df_ventas_largo.dropna(subset=["CANTIDAD_FACTURADA"])

display(df_ventas_largo.head(20))

,CODIGO_PRODUCTO,PRODUCTO,PERIODO,CANTIDAD_FACTURADA
3,2229,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,MAYO 2025,73.0
4,2278,[2278] A MILKSHAKE PLEASE DM,MAYO 2025,193053.0
6,0252,[0252] ACQUA FRESCA HM,MAYO 2025,108910.0
7,509,[509] ADDICTIVE VIBE HM,MAYO 2025,198785.0
8,0723,[0723] ADELINE DM,MAYO 2025,44195.0
9,400,[400] ADIVINA DM,MAYO 2025,20035.0
10,372,[372] ADREA HM,MAYO 2025,125210.0
11,291,[291] ADRIAN HM,MAYO 2025,137494.0
12,287,[287] ADRIANA DM,MAYO 2025,29245.0
13,2097,[2097] ADVENTUROUS SKIPPER HM,MAYO 2025,9170.0
14,2166,[2166] AEDEN UNISEX,MAYO 2025,4050.0
15,309,[309] AFFRIKA DM,MAYO 2025,40630.0
16,310,[310] AFRIKANO HM,MAYO 2025,3980.0
17,485,[485] AFRODISIO HM,MAYO 2025,23760.0
18,273,[273] AGUAMARINA HM,MAYO 2025,17970.0
19,693,[693] ALAMBRA LINA DM,MAYO 2025,10580.0
20,0001,[0001] ALCOHOL EXTRA NEUTRO.,MAYO 2025,25655.0
21,0002,[0002] ALCOHOL EXTRA NEUTRO. X 1 LTR,MAYO 2025,50.0
22,240101010003,[240101010003] ALCOHOL EXTRA NEUTRO. X GALON,MAYO 2025,785.0
23,493,[493] ALL BLACK HM,MAYO 2025,28060.0

In [21]:
print("Filas y columnas:", df_ventas_largo.shape)

Filas y columnas: (26189, 4)

In [22]:
# Eliminar cantidades en cero o negativas
df_ventas_largo = df_ventas_largo[
    df_ventas_largo["CANTIDAD_FACTURADA"] > 0
].copy()

display(df_ventas_largo.head(5))

,CODIGO_PRODUCTO,PRODUCTO,PERIODO,CANTIDAD_FACTURADA
3,2229,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,MAYO 2025,73.0
4,2278,[2278] A MILKSHAKE PLEASE DM,MAYO 2025,193053.0
6,0252,[0252] ACQUA FRESCA HM,MAYO 2025,108910.0
7,509,[509] ADDICTIVE VIBE HM,MAYO 2025,198785.0
8,0723,[0723] ADELINE DM,MAYO 2025,44195.0

In [23]:
print("Filas y columnas:", df_ventas_largo.shape)
df_ventas_largo.dtypes

Filas y columnas: (26183, 4)

CODIGO_PRODUCTO        string
PRODUCTO               string
PERIODO                   str
CANTIDAD_FACTURADA    float64
dtype: object

In [24]:
print("Filas después de limpiar ventas:", df_ventas_largo.shape[0])

display(
    df_ventas_largo
    .groupby("PERIODO")["CANTIDAD_FACTURADA"]
    .sum()
    .reset_index()
)

Filas después de limpiar ventas: 26183

            PERIODO  CANTIDAD_FACTURADA
0        ABRIL 2026          39307103.0
1       AGOSTO 2025          23512184.0
2    DICIEMBRE 2025          29811469.0
3        ENERO 2026          25239383.0
4      FEBRERO 2026          23378757.0
5        JULIO 2025          31191198.0
6        JUNIO 2025          31501012.6
7        JUNIO 2026           6774189.0
8        MARZO 2026          37864869.0
9         MAYO 2025          33999713.0
10        MAYO 2026          29016937.0
11   NOVIEMBRE 2025          29555801.0
12     OCTUBRE 2025          28736171.0
13  SEPTIEMBRE 2025          36320786.0

In [25]:
# ==============================
# 7. PREPARAR CODIGOS PARA EL CRUCE
# ==============================

df_ventas_largo["CODIGO_PRODUCTO"] = (
    df_ventas_largo["CODIGO_PRODUCTO"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", "", regex=True)
)

df_maestro["CODIGO_PRODUCTO"] = (
    df_maestro["CODIGO_PRODUCTO"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", "", regex=True)
)

In [26]:
print(df_maestro.columns)
display(df_maestro.head())

Index(['CODIGO_PRODUCTO', 'NOMBRE_PRODUCTO', 'CLASIFICACION I',
       'CLASIFICACION II', 'CLASIFICACION III', 'CLASIFICACION IV'],
      dtype='str')

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2542,ENVASE SADMAN TRANSP 105 ML PLATA CROMADO X 54...,ENVASE,SADMAN,105 ML,NO APLICA
1,2610,ENVASE SALVAJE 100 ML FUCSIA X 72 UND,ENVASE,SALVAJE,100 ML,NO APLICA
2,2608,ENVASE SALVAJE 100 ML NEGRO X 72 UND,ENVASE,SALVAJE,100 ML,NO APLICA
3,2229,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NO APLICA,NO APLICA
4,2278,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM

In [27]:
# ==============================
# 7. CRUZAR VENTAS CON TABLA MAESTRA
# ==============================

df_ventas_powerbi = df_ventas_largo.merge(
    df_maestro,
    on="CODIGO_PRODUCTO",
    how="left"
)

display(df_ventas_powerbi.head(10))

,CODIGO_PRODUCTO,PRODUCTO,PERIODO,CANTIDAD_FACTURADA,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2229,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,MAYO 2025,73.0,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NO APLICA,NO APLICA
1,2278,[2278] A MILKSHAKE PLEASE DM,MAYO 2025,193053.0,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM
2,0252,[0252] ACQUA FRESCA HM,MAYO 2025,108910.0,ACQUA FRESCA HM,ESENCIA,ESENCIA GENERAL,ARMANI,HM
3,509,[509] ADDICTIVE VIBE HM,MAYO 2025,198785.0,ADDICTIVE VIBE HM,ESENCIA,ESENCIA GENERAL,PACO RABANNE,HM
4,0723,[0723] ADELINE DM,MAYO 2025,44195.0,ADELINE DM,ESENCIA,ESENCIA NICHO,PARFUMS DE MARLY,DM
5,400,[400] ADIVINA DM,MAYO 2025,20035.0,ADIVINA DM,ESENCIA,ESENCIA GENERAL,GUESS,DM
6,372,[372] ADREA HM,MAYO 2025,125210.0,ADREA HM,ESENCIA,ESENCIA GENERAL,ENRIQUE IGLESIAS,HM
7,291,[291] ADRIAN HM,MAYO 2025,137494.0,ADRIAN HM,ESENCIA,ESENCIA GENERAL,CAROLINA HERRERA,HM
8,287,[287] ADRIANA DM,MAYO 2025,29245.0,ADRIANA DM,ESENCIA,ESENCIA GENERAL,CAROLINA HERRERA,DM
9,2097,[2097] ADVENTUROUS SKIPPER HM,MAYO 2025,9170.0,ADVENTUROUS SKIPPER HM,ESENCIA,ESENCIA GENERAL,NAUTICA,HM

In [28]:
print(df_ventas_powerbi.columns)

Index(['CODIGO_PRODUCTO', 'PRODUCTO', 'PERIODO', 'CANTIDAD_FACTURADA',
       'NOMBRE_PRODUCTO', 'CLASIFICACION I', 'CLASIFICACION II',
       'CLASIFICACION III', 'CLASIFICACION IV'],
      dtype='str')

In [29]:
productos_no_clasificados = (
    df_ventas_powerbi[
        df_ventas_powerbi["NOMBRE_PRODUCTO"].isna()
    ][["CODIGO_PRODUCTO", "PRODUCTO"]]
    .drop_duplicates()
)

display(productos_no_clasificados)

      CODIGO_PRODUCTO                                           PRODUCTO
17               0002               [0002] ALCOHOL EXTRA NEUTRO. X 1 LTR
18       240101010003       [240101010003] ALCOHOL EXTRA NEUTRO. X GALON
52               1817                        [1817] Arrendamiento Bodega
516              1685                                    [1685] ESENCIAS
809              1147                            [1147] MOOD VAINILLA DM
919              0202  [0202] PREFORMA NO. 3 ENVASE PINK - JAMES - NE...
1719             1686                                     [1686] STICKER
1784            C0006                                      [C0006] Tinas
1785             1553                                  [1553] Transporte
3634             2245                                     [2245] Tramite
11442            2565                                 [2565] Banking FEE
20824            2823                         [2823] TINA PLASTICA 200 L

In [30]:
productos_no_clasificados.to_excel(
    "Data/Tabla_Productos_No_Clasificados.xlsx",
    sheet_name="Productos",
    index=False
)

In [31]:
# Guardar registros no clasificados antes de eliminarlos
df_registros_no_clasificados = df_ventas_powerbi[
    df_ventas_powerbi["NOMBRE_PRODUCTO"].isna()
].copy()

display(df_registros_no_clasificados.head(5))

,CODIGO_PRODUCTO,PRODUCTO,PERIODO,CANTIDAD_FACTURADA,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
17,0002,[0002] ALCOHOL EXTRA NEUTRO. X 1 LTR,MAYO 2025,50.0,NaN,NaN,NaN,NaN,NaN
18,240101010003,[240101010003] ALCOHOL EXTRA NEUTRO. X GALON,MAYO 2025,785.0,NaN,NaN,NaN,NaN,NaN
52,1817,[1817] Arrendamiento Bodega,MAYO 2025,1.0,NaN,NaN,NaN,NaN,NaN
516,1685,[1685] ESENCIAS,MAYO 2025,17000.0,NaN,NaN,NaN,NaN,NaN
809,1147,[1147] MOOD VAINILLA DM,MAYO 2025,650.0,NaN,NaN,NaN,NaN,NaN

In [32]:
# Eliminar registros que no se pudieron clasificar
df_ventas_powerbi = df_ventas_powerbi[
    df_ventas_powerbi["NOMBRE_PRODUCTO"].notna()
].copy()

# Reiniciar índice
df_ventas_powerbi = df_ventas_powerbi.reset_index(drop=True)

display(df_ventas_powerbi.head())

,CODIGO_PRODUCTO,PRODUCTO,PERIODO,CANTIDAD_FACTURADA,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2229,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,MAYO 2025,73.0,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NO APLICA,NO APLICA
1,2278,[2278] A MILKSHAKE PLEASE DM,MAYO 2025,193053.0,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM
2,0252,[0252] ACQUA FRESCA HM,MAYO 2025,108910.0,ACQUA FRESCA HM,ESENCIA,ESENCIA GENERAL,ARMANI,HM
3,509,[509] ADDICTIVE VIBE HM,MAYO 2025,198785.0,ADDICTIVE VIBE HM,ESENCIA,ESENCIA GENERAL,PACO RABANNE,HM
4,0723,[0723] ADELINE DM,MAYO 2025,44195.0,ADELINE DM,ESENCIA,ESENCIA NICHO,PARFUMS DE MARLY,DM

In [33]:
registros_sin_clasificar = df_ventas_powerbi["NOMBRE_PRODUCTO"].isna().sum()

print("Registros sin clasificar:", registros_sin_clasificar)
print("Filas finales:", df_ventas_powerbi.shape[0])

Registros sin clasificar: 0
Filas finales: 26169

In [34]:
df_ventas_powerbi[
    [
        "NOMBRE_PRODUCTO",
        "CLASIFICACION I",
        "CLASIFICACION II",
        "CLASIFICACION III",
        "CLASIFICACION IV"
    ]
].isna().sum()

NOMBRE_PRODUCTO      0
CLASIFICACION I      0
CLASIFICACION II     0
CLASIFICACION III    0
CLASIFICACION IV     0
dtype: int64

In [35]:
# ==============================
# ELIMINAR REGISTROS NO CLASIFICADOS
# ==============================

df_registros_no_clasificados = df_ventas_powerbi[
    df_ventas_powerbi["NOMBRE_PRODUCTO"].isna()
].copy()

df_ventas_powerbi = df_ventas_powerbi[
    df_ventas_powerbi["NOMBRE_PRODUCTO"].notna()
].copy()

df_ventas_powerbi = df_ventas_powerbi.reset_index(drop=True)

print("Registros eliminados:", df_registros_no_clasificados.shape[0])
print("Registros finales:", df_ventas_powerbi.shape[0])

display(df_ventas_powerbi.head())

Registros eliminados: 0
Registros finales: 26169

,CODIGO_PRODUCTO,PRODUCTO,PERIODO,CANTIDAD_FACTURADA,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV
0,2229,[2229] 180 FUNDAS SURTIDAS X 6 COLORES,MAYO 2025,73.0,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NO APLICA,NO APLICA
1,2278,[2278] A MILKSHAKE PLEASE DM,MAYO 2025,193053.0,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM
2,0252,[0252] ACQUA FRESCA HM,MAYO 2025,108910.0,ACQUA FRESCA HM,ESENCIA,ESENCIA GENERAL,ARMANI,HM
3,509,[509] ADDICTIVE VIBE HM,MAYO 2025,198785.0,ADDICTIVE VIBE HM,ESENCIA,ESENCIA GENERAL,PACO RABANNE,HM
4,0723,[0723] ADELINE DM,MAYO 2025,44195.0,ADELINE DM,ESENCIA,ESENCIA NICHO,PARFUMS DE MARLY,DM

In [36]:
# ==============================
# ORDENAR COLUMNAS FINALES PARA POWER BI
# ==============================

df_ventas_powerbi = df_ventas_powerbi[
    [
        "CODIGO_PRODUCTO",
        "NOMBRE_PRODUCTO",
        "CLASIFICACION I",
        "CLASIFICACION II",
        "CLASIFICACION III",
        "CLASIFICACION IV",
        "PERIODO",
        "CANTIDAD_FACTURADA"
    ]
]

display(df_ventas_powerbi.head())

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV,PERIODO,CANTIDAD_FACTURADA
0,2229,180 FUNDAS SURTIDAS X 6 COLORES,FUNDA,PAQUETE,NO APLICA,NO APLICA,MAYO 2025,73.0
1,2278,A MILKSHAKE PLEASE DM,ESENCIA,ESENCIA NICHO,ARMAF,DM,MAYO 2025,193053.0
2,0252,ACQUA FRESCA HM,ESENCIA,ESENCIA GENERAL,ARMANI,HM,MAYO 2025,108910.0
3,509,ADDICTIVE VIBE HM,ESENCIA,ESENCIA GENERAL,PACO RABANNE,HM,MAYO 2025,198785.0
4,0723,ADELINE DM,ESENCIA,ESENCIA NICHO,PARFUMS DE MARLY,DM,MAYO 2025,44195.0

In [37]:
df_ventas_powerbi.isnull().sum()

CODIGO_PRODUCTO       0
NOMBRE_PRODUCTO       0
CLASIFICACION I       0
CLASIFICACION II      0
CLASIFICACION III     0
CLASIFICACION IV      0
PERIODO               0
CANTIDAD_FACTURADA    0
dtype: int64

In [38]:
df_ventas_powerbi.dtypes

CODIGO_PRODUCTO        string
NOMBRE_PRODUCTO           str
CLASIFICACION I           str
CLASIFICACION II          str
CLASIFICACION III         str
CLASIFICACION IV          str
PERIODO                   str
CANTIDAD_FACTURADA    float64
dtype: object

In [39]:
df_ventas_powerbi["CANTIDAD_FACTURADA"] = pd.to_numeric(
    df_ventas_powerbi["CANTIDAD_FACTURADA"],
    errors="coerce"
)

In [40]:
df_ventas_powerbi = df_ventas_powerbi.sort_values(
    by=["PERIODO", "CLASIFICACION I", "NOMBRE_PRODUCTO"]
).reset_index(drop=True)

display(df_ventas_powerbi.head())

,CODIGO_PRODUCTO,NOMBRE_PRODUCTO,CLASIFICACION I,CLASIFICACION II,CLASIFICACION III,CLASIFICACION IV,PERIODO,CANTIDAD_FACTURADA
0,0001,ALCOHOL EXTRA NEUTRO.,ALCOHOL,ALCOHOL,ALCOHOL,ALCOHOL,ABRIL 2026,32190.0
1,2780,CAJA CILINDRICA BLANCA 100 ML X 120 UND,CAJA,CILINDRICA,100 ML,NO APLICA,ABRIL 2026,120.0
2,0008,CAJA PARA CILINDRO 1OZ DORADO,CAJA,CILINDRO,1 OZ,NO APLICA,ABRIL 2026,1100.0
3,0009,CAJA PARA CILINDRO 1OZ FUCSIA,CAJA,CILINDRO,1 OZ,NO APLICA,ABRIL 2026,1750.0
4,0006,CAJA PARA CILINDRO 1OZ NEGRA,CAJA,CILINDRO,1 OZ,NO APLICA,ABRIL 2026,1750.0

In [41]:
with pd.ExcelWriter(ruta_salida_powerbi, engine="openpyxl") as writer:
    df_ventas_powerbi.to_excel(
        writer,
        sheet_name="Ventas_Limpias",
        index=False
    )

print("Archivo generado correctamente:", ruta_salida_powerbi)

Archivo generado correctamente: Resultado\Ventas_Limpias_PowerBI.xlsx